version: "3.1"
services:
  db:
    image: postgres:11.13-alpine
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5555:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    ports:
      - 8082:8080